#! /bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT="$( dirname "${DIR}" )"
E=0

pushd "${ROOT}"
    for gofile in $(find . -type f -name '*.go' | grep -v test ); do
      R="$(golint "${gofile}")"
      if [ -n "$R" ]; then
          echo "$R"
          E=$((E+1))
      fi
    done
popd

if [ "$E" -gt 0 ] then
    exit 1
fi
