[db]
user = 'ubuntu'
password = ''
host = 'localhost'
port = 3306
type = 'mysql'
dbname = 'circle_test'

[app]
port = 8080
debug = true
sockets = ["/tmp/door1", "/tmp/door2", "/tmp/door3"]
blackList = "/tmp/blacklist"

[jobs]
browsingTimer = false
httpReconstructor = false
