#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
HOME_DIR="$( dirname "$DIR")"
GOROOT="/usr/local/go"

cd "$HOME_DIR"; pushd ../../../../ > /dev/null
    GOPATH="$(pwd)"
popd > /dev/null

export GOROOT
export GOPATH


pushd "$HOME_DIR" > /dev/null
    # go list ./...
    go version
    # go test "$( go list ./... | grep -v 'vendor\|test')"
    go test "$( go list ./... | grep -v 'vendor')"
popd > /dev/null
