---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  remote_user: vagrant
  become: True

  roles:
    - common

- name: configure and deploy the devserver and application code
  hosts: devserver
  remote_user: vagrant
  become: True

  roles:
    - db
    - joshualund.golang
    - dev
