---
# This playbook contains common plays that will be run on all nodes.

- name: yum update
  yum: name=* state=latest

- name: Install common utilities
  yum: name={{ item }} state=present
  with_items:
   - vim
   - git
   - zsh
   - wget

- name: Disable SELinux
  selinux: state=disabled
